name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g npm@latest  # Needed while 14.x is supported.
      - run: npm ci
      - run: ls node_modules/.bin/ # TEST
      - run: cat node_modules/.bin/schema-dts-gen # TEST
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - run: npm run coverage_on_travis
